### ISSUE TITLE
Weird resource reset bug

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#93]
If I upload a file and then choose a tag (any tag type), the entire resource resets. I then cannot upload files ("Cannot read property 'length' of undefined") until I come out of the add resource and go back into it.

**Comment by dave-mills** [comment]
More info: Also occurs when editing exist resources. 

To recreate: 

- edit an existing resource. Add a new file, then add / edit a tag.

**Comment by chrismclarke** [comment]
So the problem is with the dirty override method that tags uses to update changes. It temporarily sets the entire resource to empty [] before repopulating. In this time the upload element loses its binding element and breaks. First attempt to fix was simply using 'notifyPath' instead of emptying, however this only ever seems to work the first time after (adding one tag only). Then realised that dirty override can be done just to a subproperty using set (e.g. this.set('resource.tags',[]); this.set('resource.tags',tagArray)). Closed with 52f68405edc4af4faa09a56865e279876e97a408
